### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!",
  	"confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmail.com",
  	"password": "John123!"
}

### GET /auth
GET http://localhost:8080/auth HTTP/1.1

### POST /auth/signout
POST http://localhost:8080/auth/signout HTTP/1.1


### GET /users
GET http://localhost:8080/users HTTP/1.1

### PATCH /users/:id
PATCH http://localhost:8080/users/41e4057a-71e9-4a18-82f2-53edb680fa95 HTTP/1.1
Content-Type: application/json

{
  	"role_id": "50cc8ef6-1477-4a80-be80-e17153aaa7db"
}
### GET /users
GET http://localhost:8080/users HTTP/1.1

### DELETE /user
DELETE http://localhost:8080/users/b2d2dbf6-a4fe-4c52-983c-3c849bc33202 HTTP/1.1

### GET /users/page
GET http://localhost:8080/users?page=1 HTTP/1.1



### GET /items
GET http://localhost:8080/items HTTP/1.1

### POST /items
POST http://localhost:8080/items HTTP/1.1
Content-Type: application/json

{
  	"title": "PC",
    "description": "zelo dober pc",
	"starting_price": 20,
	"end_date": "2025-04-05 07:43:12.760868"
}
### PATCH /items/:id
PATCH http://localhost:8080/items/4a4067cd-03a5-461f-8cda-db2fc689a406 HTTP/1.1
Content-Type: application/json

{
  	"title": "test"
}
### DELETE /item
DELETE http://localhost:8080/items/4fbdb370-390a-4bac-b0cd-9ec89c25bc00 HTTP/1.1


